services:

  node-red:
    image: nodered/node-red:3.1
    ports:
      - "1880:1880"
    volumes:
      - ./volumes/node_red_data:/data

  grafana:
    image: grafana/grafana:12.0.1
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana:/var/lib/grafana

  pg:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
      - ./volumes/pg_initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
