{
 "title": "Energiecockpit",
 "time": { "from": "2010-01-01T01:00:00.000Z", "to": "2021-11-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Energieverbrauch über Zeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT verbrauch, $__time(ts) FROM energy_consumption WHERE $__timeFilter(ts) "
    }
   ]
  },
  {
   "title": "Täglicher Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n$__timeGroup(ts, '24h'), \r\nAVG(verbrauch) as \"Durchschnittlicher Tagesvergrauch\", \r\nMAX(verbrauch) as \"Maximaler Tagesvergrauch\",\r\nMIN(verbrauch) as \"Minimaler Tagesvergrauch\",\r\nSUM(verbrauch) as \"Gesamtverbrauch\"\r\nFROM energy_consumption\r\nWHERE $__timeFilter(ts) \r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(temperature) AS \"Durchschnittstemperatur\", MIN(temperature) AS \"Minimale Temperatur\", MAX(temperature) AS \"Maximale Temperatur\" FROM energy_consumption WHERE $__timeFilter(ts) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Extremwetter Analyse (Anzahl der Tage)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    $__timeGroup(ts, '24h'),\r\n    verbrauch,\r\n    CASE \r\n        WHEN temperature < 0 THEN 'Frost'\r\n        WHEN temperature > 30 THEN 'Hitze'\r\n        ELSE 'Normal'\r\n    END as wetter_kategorie\r\nFROM energy_consumption\r\nWHERE $__timeFilter(ts) \r\nAND (\r\n    temperature < 0 OR temperature > 30\r\n)"
    }
   ]
  },
  {
   "title": "Monatlicher Durchschnittsverbrauch",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('month', ts) as time,\r\n    AVG(verbrauch)\r\nFROM energy_consumption \r\nWHERE $__timeFilter(ts) \r\nGROUP BY time\r\nORDER by time"
    }
   ]
  },
  {
   "title": " Zusammenhang zwischen Temperatur und Verbrauch",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT temperature, verbrauch FROM energy_consumption WHERE $__timeFilter(ts) ORDER BY ts ASC LIMIT 2000 "
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_direction FROM energy_consumption WHERE $__timeFilter(ts) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Durchschnitts-Windgeschwindigkeit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(wind_speed) FROM energy_consumption WHERE $__timeFilter(ts) "
    }
   ]
  }
 ]
}